### ISSUE TITLE
find-repeats use only snvphyl-tools env

### ISSUE THREAD

**Issue by Takadonet** [phac-nml/snvphyl-galaxy#11]
Galaxy Wrapper for find-repeats.xml should collapse to a single conda requirement instead of having mummer separately. However, when just using snvphyl-tools, get following error.

Can't locate Foundation.pm in @INC (you may need to install the Foundation module) (@INC contains:....)

Time to update the bioconda recipe!

**Comment by Takadonet** [comment]
Issue is that there are now multiple version of perl being installed for snvphyl and mummer. Hence, when a package is installed, it may or may not go into the correct perl version library path.

**Comment by apetkau** [comment]
Closing this issue. We are sticking with 2 conda requirements for the update.
