### ISSUE TITLE
Add Bundle collection tool to Suite and workflow 

### ISSUE THREAD

**Issue by Takadonet** [phac-nml/snvphyl-galaxy#18]
All local SNVphyl workflow use [Bundle Collection tool](https://toolshed.g2.bx.psu.edu/view/nml/bundle_collections/cd6da887a5f4) to create a single downloaded with all important output files. It make easier if new workflow releases will have Bundle Collection tool added.

**Comment by apetkau** [comment]
Fixed in #29
