### ISSUE TITLE
Conda environment for snvphyl-tools broken on centos machine

### ISSUE THREAD

**Issue by Takadonet** [phac-nml/snvphyl-galaxy#19]
Situation is where bcftools in the __snvphyl-tools@1.8.2 environment will not run due to following error:

`samtools: error while loading shared libraries: libcrypto.so.1.0.0:`

Only seems to be happening in Centos/Redhat environment where as ubuntu/deb it does not. No idea why.

Issue is related to one describe in [samtools](https://github.com/bioconda/bioconda-recipes/issues/12100)

Temporary solution is to add a soft link in the lib/ folder of the conda environment.

`cd /conda/envs/__snvphyl-tools@1.8.2/lib`

`ln -s libcrypto.so.1.1 libcrypto.so.1.0.0`

Long term solution would be to fix the bioconda recipe to ensure we get the correct version of opensll.

**Comment by apetkau** [comment]
Fixed in https://github.com/bioconda/bioconda-recipes/pull/22880
