### ISSUE TITLE
Pseudo-whole genome alignment from SNVPhyl?

### ISSUE THREAD

**Issue by cizydorczyk** [phac-nml/snvphyl-galaxy#20]
Hello,

I was wondering if anyone could offer some insight as to how I could obtain a pseudo-whole genome alignment from SNVPhyl? What I mean by pseudo alignment is a whole genome alignment where each isolate is assumed to be the same length as the reference with SNPs implanted on the reference sequence, but with low coverage, indels, gaps, etc. all masked. In essence, something equivalent to the `.full.aln` alignment produced by Snippy-core (https://github.com/tseemann/snippy).

I am interested in comparing SNVPhyl density filtering with Gubbins for _H. influenzae_ but require whole genome alignments for Gubbins, whereas SNVPhyl only outputs a SNV alignment.

I think this should be quite possible...from what I've been able to gather, SNVPhyl generates bcf files marking each position in the reference as either a high-quality SNV or high quality non-variant base call. I was thinking of using these files to simply generate an "alignment", but I'm not sure where I can find these files.

I run SNVPhyl v. 1.0.1 on Galaxy directly from a virtual machine (no docker, no vagrant, etc.).

I was wondering if anybody could offer some insight as to where I could find these files, or an alternate approach to running Gubbins on SNVs from SNVPhyl?

Any response is greatly appreciated!!

Thank you,
Conrad Izydorczyk

**Comment by apetkau** [comment]
Hello Conrad,

If you have SNVPhyl installed via Galaxy it should come with a tool **Positions to SNV invariant alignment**:

![image](https://user-images.githubusercontent.com/200517/64479493-8db3d180-d17d-11e9-83ad-04e73c1153f0.png)

This should do exactly what you are looking for. If you cannot find it in Galaxy, the code it will run is located here https://github.com/phac-nml/snvphyl-tools/blob/master/bin/positions2snv_invariant_alignment.pl.

**Comment by cizydorczyk** [comment]
Oh wow, I don't know how I missed that. Thank you so much!

**Comment by apetkau** [comment]
No problem. I think it's hidden away (we should probably add a bit more in our docs). But, I'm glad it solves your problem.

**Comment by cizydorczyk** [comment]
Hello,

I have a quick question regarding the "keep all positions" option. From a quick comparison I performed, it seems that setting this to 'yes' leads to gaps and 'N's being included in the final alignment, presumably at sites that were filtered, whereas setting this to 'no' does not (and reference bases are placed into these positions instead) -- is this correct?

Thank you,
Conrad

**Comment by apetkau** [comment]
@cizydorczyk yes that's correct. This is added in case you wanted to keep all the positions with gaps or an N character for further processing. Leaving this data in can give additional details which may be used by Gubbins when looking for recombination.

**Comment by cizydorczyk** [comment]
Great! Thank you!
