### ISSUE TITLE
SNVPhyl Density Filtering Step Size?

### ISSUE THREAD

**Issue by cizydorczyk** [phac-nml/snvphyl-galaxy#22]
Hello,

A quick clarification question (as I am not great with C-code and the bcftools plugin for density filtering is almost nonsensical to me!) -- would it be correct to assume that SNVPhyl's sliding window moves across the genome 1 base at a time, and NOT by window size? 

(i.e. first window at position 1, second at position 2, etc. and NOT first window at position 1, second window at position 501, etc. for a 500bp sliding window)

Thank you!!
Conrad

**Comment by apetkau** [comment]
Hello @cizydorczyk 

Sorry about the (very) late response. I must have missed this when it was first posted.

The window does not slide along the entire genome. It's based only on identified SNVs. That is, it slides along SNVs identified by FreeBayes and counts the number within **window_size** of each other. If this number exceeds the threshold then the identified region (start/end positions of SNVs) is printed.
