### ISSUE TITLE
smalt

### ISSUE THREAD

**Issue by deearahman** [phac-nml/snvphyl-galaxy#3]
I ran my analysis yesterday. It has been at smalt step since. Does it usually take very long to run smalt mapping?

**Comment by apetkau** [comment]
It can take a while to run some of the smalt stages depending on the size of your data and number of genomes you are trying to process

Is it just one smalt mapping job that is taking a long time, or many smalt jobs?  How are you running SNVPhyl (via the Docker Galaxy image)?
