### ISSUE TITLE
tool_script.sh: line 9: find-repeats.pl: command not found

### ISSUE THREAD

**Issue by innovate-invent** [phac-nml/snvphyl-galaxy#36]
https://github.com/phac-nml/snvphyl-galaxy/blob/1af858f56d39eda94481ba777afdb793dc651ae3/tools/snvphyl-tools/find_repeats/find-repeats.xml#L10

This file is not included with the tool wrapper. What provides it?

**Comment by apetkau** [comment]
This is provided in a conda package `snvphyl-tools` which is referenced in a macros file as a dependency https://github.com/phac-nml/snvphyl-galaxy/blob/development/tools/snvphyl-tools/macros.xml#L6

**Comment by innovate-invent** [comment]
ah, I wonder if that is confusing the dependency mulling code from detecting it

**Comment by innovate-invent** [comment]
I understand now, this tool is not having a container built because the tool has multiple dependencies and the repo is not included in https://github.com/galaxyproject/planemo-monitor

Would you prefer to publish your own container or can I submit a PR to planemo-monitor?

**Comment by apetkau** [comment]
Yes, please submit a PR to planemo-monitor. Is there anything else they require (e.g., files to be in specific locations on GitHub)?

**Comment by innovate-invent** [comment]
https://github.com/galaxyproject/planemo-monitor/pull/38

The program will recursively scan the repository for tool xml files. I opened https://github.com/galaxyproject/planemo-monitor/pull/37 to restrict that. If it is accepted, we should probably add the path to the first PR.

**Comment by apetkau** [comment]
Ah, okay. And so my understanding of `planemo-monitor` is that it looks for tools that lack Docker images/have multiple requirements and builds special Docker images for these requirements? So if that PR is submitted we would just give it the path `https://github.com/phac-nml/snvphyl-galaxy/tree/development/tools/snvphyl-tools` and it would look only for tool XML files under that directory and build any missing Docker images (and specifically build a Docker image for the `find-repeats.xml` tool)?

**Comment by innovate-invent** [comment]
The path to add would be `/tools/snvphyl-tools/`. I think that is the only place in your repo that contains tools.

Yes, it will build containers with all of the required dependencies and publish them to the mulled biocontainers project.

**Comment by innovate-invent** [comment]
This tool is still waiting on https://github.com/bioconda/bioconda-recipes/pull/29165 to filter through to the mulled container

**Comment by innovate-invent** [comment]
The mulled container had to manually have its build number bumped: https://github.com/BioContainers/multi-package-containers/pull/1773
